version: '3'
services:
  static-server:
    image: davyinsa/cloudrup-static-server
    container_name: static-server
    restart: always
    environment: 
      - APACHE_MAX_THREAD=100
    volumes:
      - ./aegir:/var/aegir
    ports:
      - "80:80"
      - "22:22"
